export const productData = [
  {
    id: 1,
    brand: "Yonex",
    name: "Yonex Astrox 100zz",
    priceBefore: 788.0,
    priceAfter: 748.6,
    discount: 5,
    rating: 4.5,
    category: "Racquet",
    url: "/images/racquet/yonex voltric zforce 2.png",
  },
  {
    id: 2,
    brand: "Felet",
    name: "Felet Aero Carbon Lite",
    priceBefore: 150.0,
    priceAfter: 135.0,
    discount: 10,
    rating: 4.7,
    category: "Racquet",
    url: "/images/racquet/felet aero carbon lite.png",
  },
  {
    id: 3,
    brand: "Li-Ning",
    name: "Li-Ning Frame N55-II",
    priceBefore: 677.0,
    priceAfter: 473.9,
    discount: 30,
    rating: 4.3,
    category: "Racquet",
    url: "/images/racquet/LiNig Frame N55-ll.png",
  },
  {
    id: 4,
    brand: "Li-Ning",
    name: "Li-Ning Lightning 2020",
    priceBefore: 350.0,
    priceAfter: 315.0,
    discount: 10,
    rating: 4.4,
    category: "Racquet",
    url: " /images/racquet/LiNing Lightning2020.png",
  },
  {
    id: 5,
    brand: "Li-Ning",
    name: "Li-Ning Aeronaut 8000",
    priceBefore: 850.0,
    priceAfter: 807.5,
    discount: 5,
    rating: 3.9,
    category: "Racquet",
    url: "/images/racquet/Lining Aeronaut 8000.png",
  },
  {
    id: 6,
    brand: "Li-Ning",
    name: "Li-Ning Storm N77 Professional",
    priceBefore: 549.0,
    priceAfter: 494.1,
    discount: 10,
    rating: 3,
    category: "Racquet",
    url: "/images/racquet/LiNing Storm N77 Professional Badminton Racquet.png",
  },
  {
    id: 7,
    brand: "Victor",
    name: "Victor AuraSpeed 80x",
    priceBefore: 350.0,
    priceAfter: 315.0,
    discount: 10,
    rating: 4.6,
    category: "Racquet",
    url: "/images/racquet/victor auraspeed 80x.png",
  },
  {
    id: 8,
    brand: "Victor",
    name: "Victor AuraSpeed 90s",
    priceBefore: 400.0,
    priceAfter: 360.0,
    discount: 10,
    rating: 4.2,
    category: "Racquet",
    url: "/images/racquet/victor auraspeed 90s.png",
  },
  {
    id: 9,
    brand: "Victor",
    name: "Victor Thruster k900",
    priceBefore: 200.0,
    priceAfter: 180.0,
    discount: 10,
    rating: 4.4,
    category: "Racquet",
    url: "/images/racquet/victor thruster k9900.png",
  },
  {
    id: 10,
    brand: "Yonex",
    name: " Arcsaber Lite",
    priceBefore: 150.0,
    priceAfter: 120.0,
    discount: 20,
    rating: 4.1,
    category: "Racquet",
    url: "/images/racquet/Yonex arcsaberlite.png",
  },
  {
    id: 11,
    brand: "Yonex",
    name: "Astrox 66",
    priceBefore: 349.0,
    priceAfter: 314.1,
    discount: 10,
    rating: 4.6,
    category: "Racquet",
    url: "/images/racquet/yonex astrox 66.png",
  },
  {
    id: 12,
    brand: "Yonex",
    name: "Yonex Astrox 77",
    priceBefore: 570.0,
    priceAfter: 513.0,
    discount: 10,
    rating: 4.1,
    category: "Racquet",
    url: "/images/racquet/yonex astrox 77.png",
  },
  {
    id: 13,
    brand: "Li-Ning",
    name: "Li-Ning ABP041",
    priceBefore: 340.0,
    priceAfter: 306.0,
    discount: 10,
    rating: 4,
    category: "Shoe",
    url: "/images/shoes/Lining ABP041.png",
  },
  {
    id: 14,
    brand: "Li-Ning",
    name: "Li-Ning AYAR011",
    priceBefore: 234.0,
    priceAfter: 210.6,
    discount: 10,
    rating: 4.1,
    category: "Shoe",
    url: "/images/shoes/Lining Ayar011 shoe.png",
  },
  {
    id: 15,
    brand: "Li-Ning",
    name: "Lining Footwear1",
    priceBefore: 167.0,
    priceAfter: 150.3,
    discount: 10,
    rating: 4.7,
    category: "Shoe",
    url: "/images/shoes/Lining Footwear 1.png",
  },
  {
    id: 16,
    brand: "Yonex",
    name: "Yonex Power Cushion 65z2 Men",
    priceBefore: 450.0,
    priceAfter: 360.0,
    discount: 20,
    rating: 4.8,
    category: "Shoe",
    url: "/images/shoes/yonex power cushion 65z men.png",
  },
  {
    id: 17,
    brand: "Yonex",
    name: "Yonex Power Cushion 65z2 KM",
    priceBefore: 450.0,
    priceAfter: 405.0,
    discount: 10,
    rating: 4.4,
    category: "Shoe",
    url: "/images/shoes/yonex power cushion 65z2 KM.png",
  },
  {
    id: 18,
    brand: "Yonex",
    name: "Yonex Power Cushion Aerus 3 Black",
    priceBefore: 467.0,
    priceAfter: 373.6,
    discount: 20,
    rating: 4.1,
    category: "Shoe",
    url: "/images/shoes/yonex power cushion aerus 3 black.png",
  },
  {
    id: 19,
    brand: "Yonex",
    name: "Yonex Power Cushion Comfort Z",
    priceBefore: 467.0,
    priceAfter: 373.6,
    discount: 20,
    rating: 4.1,
    category: "Shoe",
    url: "/images/shoes/yonex power cushion comfort z.png",
  },
  {
    id: 20,
    brand: "Yonex",
    name: "Yonex Duora10 LCW",
    priceBefore: 549.0,
    priceAfter: 494.1,
    discount: 10,
    rating: 4.4,
    category: "Racquet",
    url: "/images/racquet/yonex duora10.png",
  },
  {
    id: 21,
    brand: "Yonex",
    name: "Yonex Voltric Zforce 2",
    priceBefore: 549.0,
    priceAfter: 494.1,
    discount: 10,
    rating: 4.5,
    category: "Racquet",
    url: "/images/racquet/yonex voltric zforce 2.png",
  },
  {
    id: 22,
    brand: "Felet",
    name: "Felet Col5018 Blue",
    priceBefore: 59.0,
    priceAfter: 53.1,
    discount: 10,
    rating: 4.1,
    category: "Tshirt",
    url: "/images/tshirt/felet col5018 blue.png",
  },
  {
    id: 23,
    brand: "Felet",
    name: "Felet Col5513",
    priceBefore: 59.0,
    priceAfter: 53.1,
    discount: 10,
    rating: 4.4,
    category: "Tshirt",
    url: "/images/tshirt/felet col5513.png",
  },
  {
    id: 24,
    brand: "Li-Ning",
    name: " Li-Ning Surdirman Black",
    priceBefore: 69.0,
    priceAfter: 62.1,
    discount: 10,
    rating: 4.5,
    category: "Tshirt",
    url: "/images/tshirt/Lining shirts sudirman 326.png",
  },
  {
    id: 25,
    brand: "Li-Ning",
    name: "Li-Ning Surdirman Blue",
    priceBefore: 69.0,
    priceAfter: 62.1,
    discount: 10,
    rating: 4.5,
    category: "Tshirt",
    url: "/images/tshirt/Untitled.png",
  },
];

export const featureProduct = [
  productData[19],
  productData[20],
  productData[21],
];
