export const data = [
  {
    id: 1,
    brand: "Yonex",
    name: "Yonex1",
    priceBefore: 400.0,
    priceAfter: 320.0,
    discount: 20,
    productrating: 5,
    category: "Shoe",
  },
  {
    id: 2,
    brand: "Yonex",
    name: "Yonex2",
    priceBefore: 300.0,
    priceAfter: 255.0,
    discount: 15,
    productrating: 1,
    category: "Racquet",
  },
  {
    id: 3,
    brand: "Yonex",
    name: "Yonex3",
    priceBefore: 554.0,
    priceAfter: 443.2,
    discount: 20,
    productrating: 6,
    category: "Racquet",
  },
  {
    id: 4,
    brand: "Yonex",
    name: "Yonex4",
    priceBefore: 225.0,
    priceAfter: 157.5,
    discount: 30,
    productrating: 6,
    category: "Racquet",
  },
  {
    id: 5,
    brand: "Yonex",
    name: "Yonex5",
    priceBefore: 775.0,
    priceAfter: 658.75,
    discount: 15,
    productrating: 4,
    category: "Racquet",
  },
  {
    id: 6,
    brand: "Lining",
    name: "Lining6",
    priceBefore: 334.0,
    priceAfter: 167.0,
    discount: 50,
    productrating: 2,
    category: "Shoe",
  },
  {
    id: 7,
    brand: "Lining",
    name: "Lining7",
    priceBefore: 133.0,
    priceAfter: 79.8,
    discount: 40,
    productrating: 3,
    category: "Shoe",
  },
  {
    id: 8,
    brand: "Felet",
    name: "Felet8",
    priceBefore: 345.0,
    priceAfter: 241.5,
    discount: 30,
    productrating: 5,
    category: "Shoe",
  },
  {
    id: 9,
    brand: "Felet",
    name: "Felet9",
    priceBefore: 775.0,
    priceAfter: 620.0,
    discount: 20,
    productrating: 3,
    category: "Tshirt",
  },
  {
    id: 10,
    brand: "Felet",
    name: "Felet10",
    priceBefore: 346.0,
    priceAfter: 311.4,
    discount: 10,
    productrating: 2,
    category: "Tshirt",
  },
  {
    id: 11,
    brand: "Victor",
    name: "Victor11",
    priceBefore: 123.0,
    priceAfter: 118.08,
    discount: 4,
    productrating: 5,
    category: "Tshirt",
  },
  {
    id: 12,
    brand: "Victor",
    name: "Victor12",
    priceBefore: 673.0,
    priceAfter: 573.0,
    discountAfter: 538.4,
    discount: 20,
    rating: 2,
    category: "Racquet",
  },
];
